[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/mechanic"
  to = "/standalone.html"
  status = 200

[[redirects]]
  from = "/customer"
  to = "/customer.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
